apiVersion: v1
kind: Pod
metadata:
  name: test-violate-latest
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest  # Vi phạm: dùng tag :latest
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
