apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: ghcr-image-signature-policy
spec:
  images:
    - glob: "ghcr.io/dvquyet/**"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElrJkImSz1PM4g3PW0Ncir5yy8T9m
          PL6vABTSSGMF76BL+q0+SpfA58z98XEVB6jt5hkZ2ToGi8eW7cshveSekg==
          -----END PUBLIC KEY-----
